In [1]:
import cv2
import numpy as np
import math
import matplotlib.pyplot as plt
A=(0,80)
B=(80,80)
C=(80,0)
D=(0,0)

In [2]:
list_x=[]
list_y=[]
def onMouse(event,x,y,flags,params):
    if event==cv2.EVENT_LBUTTONDOWN:
        print(x,y)
        list_x.append(x)
        list_y.append(y)
    return list_x,list_y

In [3]:
img = cv2.imread('D:/test_pic/hbt.jpg',1)
cv2.imshow('sample',img)
cv2.setMouseCallback('sample',onMouse)
cv2.waitKey(0)

249 219
605 221
599 568
248 564


-1

In [4]:
#得到图像上的坐标了
print(list_x)
print("***********")
print(list_y)

[249, 605, 599, 248]
***********
[219, 221, 568, 564]


In [5]:
x = np.asarray([list_x])
y = np.asarray([list_y])
print(x)
print(y)

[[249 605 599 248]]
[[219 221 568 564]]


In [6]:
M = np.hstack((x.T,y.T))
M

array([[249, 219],
       [605, 221],
       [599, 568],
       [248, 564]])

In [7]:
#构造系数矩阵
A=np.array([[M[0,0],M[0,1],1,0,0,0,-M[0,0],-M[0,1],-1],
            [0,0,0,M[0,0],M[0,1],1,-M[0,0],-M[0,1],-1],
            [M[1,0],M[1,1],1,0,0,0,-M[1,0],-M[1,1],-1],
            [0,0,0,M[1,0],M[1,1],1,-M[1,0],-M[1,1],-1],
            [M[2,0],M[2,1],1,0,0,0,-M[2,0],-M[2,1],-1],
            [0,0,0,M[2,0],M[2,1],1,-M[2,0],-M[2,1],-1],
            [M[3,0],M[3,1],1,0,0,0,-M[3,0],-M[3,1],-1],
            [0,0,0,M[3,0],M[3,1],1,-M[3,0],-M[3,1],-1],
            [M[0,0]-M[1,0],M[0,1]-M[1,1],0,0,0,0,-M[0,0]+M[1,0],-M[0,1]+M[1,1],0]])
print(A)
#构造右侧矩阵b
b=np.array([-1,79,79,79,79,-1,-1,-1,-80])
print(b)

[[ 249  219    1    0    0    0 -249 -219   -1]
 [   0    0    0  249  219    1 -249 -219   -1]
 [ 605  221    1    0    0    0 -605 -221   -1]
 [   0    0    0  605  221    1 -605 -221   -1]
 [ 599  568    1    0    0    0 -599 -568   -1]
 [   0    0    0  599  568    1 -599 -568   -1]
 [ 248  564    1    0    0    0 -248 -564   -1]
 [   0    0    0  248  564    1 -248 -564   -1]
 [-356   -2    0    0    0    0  356    2    0]]
[ -1  79  79  79  79  -1  -1  -1 -80]


In [8]:
x = np.linalg.solve(A,b)
print(x)
H=x.reshape(3,3)
print(H)

LinAlgError: Singular matrix

In [ ]:
test_x=[]
test_y=[]
def on_Mouse_test(event,x,y,flags,params):
    if event==cv2.EVENT_LBUTTONDOWN:
        print(x,y)
        test_x.append(x)
        test_y.append(y)
    return test_x,test_y

In [ ]:
img = cv2.imread('D:/test_pic/hbt.jpg',1)
cv2.imshow('sample',img)
cv2.setMouseCallback('sample',on_Mouse_test)
cv2.waitKey(0)

In [ ]:
x_test = np.asarray([test_x])
y_test = np.asarray([test_y])
M_test=np.hstack((x_test.T,y_test.T))
print(M_test)
print(M_test.shape)

In [ ]:
T_y_1 = np.array([M[0,0],M[0,1],1])
T_1 = H.dot(T_y_1.T)
print(T_1[0]/T_1[2])
print(T_1[1]/T_1[2])