In [46]:
import cv2
import numpy as np
import math
import matplotlib.pyplot as plt
#现实坐标
X=np.array([[0,11,12],
           [0,29,42],
           [9,0,11],
           [32,0,39],
            [11,9,0],
            [30,20,0]])

In [47]:
X[0,0],X[0,1],X[0,2]

(0, 11, 12)

In [48]:
list_x=[]
list_y=[]
def onMouse(event,x,y,flags,params):
    if event==cv2.EVENT_LBUTTONDOWN:
        print(x,y)
        list_x.append(x)
        list_y.append(y)
    return list_x,list_y

In [59]:
img = cv2.imread('D:/test_pic/dlt2.jpg',1)
cv2.imshow('sample',img)
cv2.setMouseCallback('sample',onMouse)
cv2.waitKey(0)

924 292
981 230
853 311
803 281
907 363
910 419


-1

In [60]:
x = np.asarray([list_x])
y = np.asarray([list_y])
print(x)
print(y)

[[925 984 852 805 907 910 924 981 853 803 907 910]]
[[291 231 309 283 364 422 292 230 311 281 363 419]]


In [61]:
M = np.hstack((x.T,y.T))
M

array([[925, 291],
       [984, 231],
       [852, 309],
       [805, 283],
       [907, 364],
       [910, 422],
       [924, 292],
       [981, 230],
       [853, 311],
       [803, 281],
       [907, 363],
       [910, 419]])

In [62]:
#构造系数矩阵
A=np.array([[-X[0,0],-X[0,1],-X[0,2],-1,0,0,0,0,M[0,0]*X[0,0],M[0,0]*X[0,1],M[0,0]*X[0,2],M[0,0]],
            [0,0,0,0,-X[0,0],-X[0,1],-X[0,2],-1,M[0,1]*X[0,0],M[0,1]*X[0,1],M[0,1]*X[0,2],M[0,1]],#1
            [-X[1,0],-X[1,1],-X[1,2],-1,0,0,0,0,M[1,0]*X[1,0],M[1,0]*X[1,1],M[1,0]*X[1,2],M[1,0]],
            [0,0,0,0,-X[1,0],-X[1,1],-X[1,2],-1,M[1,1]*X[1,0],M[1,1]*X[1,1],M[1,1]*X[1,2],M[1,1]],#2
            [-X[2,0],-X[2,1],-X[2,2],-1,0,0,0,0,M[2,0]*X[2,0],M[2,0]*X[2,1],M[2,0]*X[2,2],M[2,0]],
            [0,0,0,0,-X[2,0],-X[2,1],-X[2,2],-1,M[2,1]*X[2,0],M[2,1]*X[2,1],M[2,1]*X[2,2],M[2,1]],#3
            [-X[3,0],-X[3,1],-X[3,2],-1,0,0,0,0,M[3,0]*X[3,0],M[3,0]*X[3,1],M[3,0]*X[3,2],M[3,0]],
            [0,0,0,0,-X[3,0],-X[3,1],-X[3,2],-1,M[3,1]*X[3,0],M[3,1]*X[3,1],M[3,1]*X[3,2],M[3,1]],#4
            [-X[4,0],-X[4,1],-X[4,2],-1,0,0,0,0,M[4,0]*X[4,0],M[4,0]*X[4,1],M[4,0]*X[4,2],M[4,0]],
            [0,0,0,0,-X[4,0],-X[4,1],-X[4,2],-1,M[4,1]*X[4,0],M[4,1]*X[4,1],M[4,1]*X[4,2],M[4,1]],#5
            [-X[5,0],-X[5,1],-X[5,2],-1,0,0,0,0,M[5,0]*X[5,0],M[5,0]*X[5,1],M[5,0]*X[5,2],M[5,0]],
            [0,0,0,0,-X[5,0],-X[5,1],-X[5,2],-1,M[5,1]*X[5,0],M[5,1]*X[5,1],M[5,1]*X[5,2],M[5,1]]   
           ])
b=np.array([0,0,0,0,0,0,0,0,0,0,0,0])
A

array([[    0,   -11,   -12,    -1,     0,     0,     0,     0,     0,
        10175, 11100,   925],
       [    0,     0,     0,     0,     0,   -11,   -12,    -1,     0,
         3201,  3492,   291],
       [    0,   -29,   -42,    -1,     0,     0,     0,     0,     0,
        28536, 41328,   984],
       [    0,     0,     0,     0,     0,   -29,   -42,    -1,     0,
         6699,  9702,   231],
       [   -9,     0,   -11,    -1,     0,     0,     0,     0,  7668,
            0,  9372,   852],
       [    0,     0,     0,     0,    -9,     0,   -11,    -1,  2781,
            0,  3399,   309],
       [  -32,     0,   -39,    -1,     0,     0,     0,     0, 25760,
            0, 31395,   805],
       [    0,     0,     0,     0,   -32,     0,   -39,    -1,  9056,
            0, 11037,   283],
       [  -11,    -9,     0,    -1,     0,     0,     0,     0,  9977,
         8163,     0,   907],
       [    0,     0,     0,     0,   -11,    -9,     0,    -1,  4004,
         3276,     0

In [63]:
#行列式值不为0
np.linalg.det(A)

1.4823251188760435e+19

In [72]:
s,v,d = np.linalg.svd(A)

In [73]:
R = d[:,-1]
R

array([ 2.98403353e-02,  1.51279614e-02,  1.49982827e-02, -9.99326649e-01,
        4.79678431e-04,  6.98659341e-04,  1.24204224e-04, -2.45377197e-04,
        9.86003541e-05,  9.09496954e-05, -2.19432356e-04,  1.06775195e-03])

In [83]:
R=R.reshape(3,4)
R

array([[ 2.98403353e-02,  1.51279614e-02,  1.49982827e-02,
        -9.99326649e-01],
       [ 4.79678431e-04,  6.98659341e-04,  1.24204224e-04,
        -2.45377197e-04],
       [ 9.86003541e-05,  9.09496954e-05, -2.19432356e-04,
         1.06775195e-03]])

In [87]:
H=R[:,:3]
H

array([[ 2.98403353e-02,  1.51279614e-02,  1.49982827e-02],
       [ 4.79678431e-04,  6.98659341e-04,  1.24204224e-04],
       [ 9.86003541e-05,  9.09496954e-05, -2.19432356e-04]])

In [88]:
h=R[:,-1]
h

array([-9.99326649e-01, -2.45377197e-04,  1.06775195e-03])

In [89]:
H_1 = np.linalg.inv(H)
H_1

array([[   46.85388362, -1333.17711143,  2447.86855697],
       [  -33.44676182,  2284.77780607,  -992.8569287 ],
       [    7.1905381 ,   347.93460631, -3868.79740466]])

In [91]:
Q,r = np.linalg.qr(H_1)
Q,r

(array([[-0.8076244 , -0.44806361, -0.38338209],
        [ 0.5765247 , -0.73658804, -0.35363447],
        [-0.12394392, -0.50663307,  0.85320621]]),
 array([[  -58.01444755,  2350.81282385, -2069.85100489],
        [    0.        , -1261.8670259 ,  1594.58642   ],
        [    0.        ,     0.        , -3888.24249219]]))

In [94]:
K=np.linalg.inv(r)
print(K)

[[-0.01723709 -0.03211207 -0.00399339]
 [-0.         -0.00079248 -0.000325  ]
 [-0.         -0.         -0.00025719]]


In [93]:
R = Q.T
print(R)

[[-0.8076244   0.5765247  -0.12394392]
 [-0.44806361 -0.73658804 -0.50663307]
 [-0.38338209 -0.35363447  0.85320621]]


In [92]:
t = r*h
t

array([[57.97538344, -0.57683586, -2.21008745],
       [-0.        ,  0.30963339,  1.70262276],
       [-0.        , -0.        , -4.15167851]])