In [1]:
import cv2
import numpy as np
import math
import matplotlib.pyplot as plt
#现实坐标
X=np.array([[31,28],
          [59,63],
            [30,62],
            [59,32],
        [31,28],
          [59,63],
           [30,62],
            [59,32]])

In [2]:
list_x=[]
list_y=[]
def onMouse(event,x,y,flags,params):
    if event==cv2.EVENT_LBUTTONDOWN:
        print(x,y)
        list_x.append(x)
        list_y.append(y)
    return list_x,list_y

In [3]:
img = cv2.imread('D:/test_pic/hbt.jpg',1)
cv2.imshow('sample',img)
cv2.setMouseCallback('sample',onMouse)
cv2.waitKey(0)

250 216
486 219
485 451
249 452


-1

In [4]:
img_1 = cv2.imread('D:/test_pic/hbt_1.jpg',1)
cv2.imshow('sample_1',img_1)
cv2.setMouseCallback('sample_1',onMouse)
cv2.waitKey(0)

416 457
600 477
565 643
370 617


-1

In [5]:
x = np.asarray([list_x])
y = np.asarray([list_y])
print(x)
print(y)

[[250 486 485 249 416 600 565 370]]
[[216 219 451 452 457 477 643 617]]


In [6]:
M = np.hstack((x.T,y.T))
M

array([[250, 216],
       [486, 219],
       [485, 451],
       [249, 452],
       [416, 457],
       [600, 477],
       [565, 643],
       [370, 617]])

In [7]:
h,s = cv2.findHomography(X,M,cv2.RANSAC,5)
h,s

(array([[-6.12652562e+00, -8.89011194e-01,  4.23102402e+02],
        [-5.75439142e+00, -1.86161044e+00,  4.59327385e+02],
        [-1.25606637e-02, -3.92598617e-03,  1.00000000e+00]]),
 array([[0],
        [1],
        [1],
        [1],
        [1],
        [0],
        [0],
        [0]], dtype=uint8))

In [9]:
rimg = cv2.warpPerspective(img_1,h,(img_1.shape[1],img_1.shape[0]))
cv2.imshow('rrr',rimg)
cv2.waitKey(0)

-1